### PR TITLE
Added Package.pins for Swift 3.1 compatibility

### PR DESCRIPTION
**Pull request by FabrizioBrancati**
I've added `Package.pins` in `.gitignore`, `Clean.swift` and `CleanTests.swift` files to support Swift 3.1.

It's just a small pull request to add Swift 3.1 compatibility, because [Xcode 8.3 beta documentation](http://adcdownload.apple.com/Developer_Tools/Xcode_8.3_beta/Release_Notes_for_Xcode_8.3_beta.pdf) says that now `Packages` folder no longer exist, until you manually edit a package with `swift package edit` command.

Fetched packages are now in `.build` folder and for example [this](https://github.com/vapor/toolbox/blob/master/Sources/VaporToolbox/Build.swift#L41) and [this](https://github.com/vapor/toolbox/blob/master/Sources/VaporToolbox/Build.swift#L45) lines won't work.

### CODE REVIEW

**Comment by vzsg** [comment]
Package.pins, just like Podfile.lock in Cocoapods, is not meant to be ignored from source control. How exactly does this help compatibility with 3.1?

**Comment by FabrizioBrancati** [comment]
It can be useful in this repository to know what version of vapor/json and vapor/console has been pinned, but can be confusing, because if one of this repositories will be updated, vapor/toolbox will not use it, as wrote [here](https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md#package-pinning).

I can remove it from .gitignore if you prefer, but if I want to clean my project I want to remove it too, this is why I added it to Clean.swift & CleanTest.swift files

**Comment by tannernelson** [comment]
If someone was relying on the Package.pins and it got deleted, that could be bad. Especially since it's using `rm -rf` so there's no way to recover it.

But I do think it's a pain to manually delete the `.pins` file if you aren't wanting it. Perhaps we could do something like `vapor clean --pins`? That would work the same way as `vapor clean --xcode` does.

**Comment by FabrizioBrancati** [comment]
I agree to your proposed, adding a `--pins` could resolve it.
I will also remove `Packages.pins` from `.gitignore`.

Can I make it, or we want to wait for the approval of someone else?

**Comment by LoganWright** [comment]
@FabrizioBrancati I'm fine with having it in the .gitignore for our Vapor projects (in fact, prefer it right now), but we can't merge this into toolbox without adding the `--pins` flag to protect people. As Tanner mentioned, rm-rf is unrecoverable and could break someone's project.

**Comment by FabrizioBrancati** [comment]
I've added `pins` parameter in `Clean.swift` file and `testCleanWithPins()` test in `CleanTests.swift` file.

**Pull request merged**
