### PR TITLE
Removed deprecated --enable-test-discovery flag from build and run commands

### PR DESCRIPTION
**Pull request by Ventus218**
Removing this flag fixes a warning which appears every time an app is built or run through the toolbox.

### Current behaviour:
```shell
vapor build
```
Output:
```shell
Building project...
warning: '--enable-test-discovery' option is deprecated; tests are automatically discovered on all platforms
```

The `--enable-test-discovery` flag is not needed anymore as deprecated because now it is the default behaviour.

### CODE REVIEW

**Review by 0xTim — CHANGES_REQUESTED** [review]
Since we still support Swift 5.2 (where test discovery is still required) I think we need to account for this case. What we should probably do is run `swift --version`, parse the output and choose the correct command to run

**Comment by Ventus218** [comment]
Yes i just realized that after submitting the PR.
I'm already working on it!

**Review by 0xTim — APPROVED** [review]

**Comment by 0xTim** [comment]
Blocked by #374

**Comment by 0xTim** [comment]
@Ventus218 can you merge in the latest changes to get CI working?

**Comment by 0xTim** [comment]
@Ventus218 is this ready to go?

**Comment by Ventus218** [comment]
> @Ventus218 is this ready to go?

Yes it is.

There is just one thing that could be added if you think that it may be valuable.
> Here [sripts/build.swift](https://github.com/vapor/toolbox/blob/7575fe2faf21dd4e856fe9e1a7b4f5db6d5222b3/scripts/build.swift#L13) the flag is set to build the toolbox, do you think we should implement the improvement here too??

**Comment by 0xTim** [comment]
@Ventus218 ah sorry I missed that question. Yep I think we probably should change that as well, but happy to do it in a separate PR if you want

**Comment by Ventus218** [comment]
One last thing. 😇

I was thinking that we could add a test like this:
```swift
    /// Assures that when Swift version can be detected it produces the right result.
    /// - Note: As this test relies on conditional compilation it can only test one specific version (the one which is currently compiling the test).
    func testSwiftVersionDetection() throws {
        if let version = VaporToolbox.RuntimeSwiftVersion() {
#if swift(>=5.5)
            XCTAssertTrue(version.major > 5 || (version.major == 5 && version.minor >= 5))
#elseif swift(>=5.4)
            XCTAssertTrue(version.major == 5 && version.minor == 4)
#elseif swift(>=5.3)
            XCTAssertTrue(version.major == 5 && version.minor == 3)
#elseif swift(>=5.2)
            XCTAssertTrue(version.major == 5 && version.minor == 2)
#else
            XCTAssertTrue( !(version.major > 5 || (version.major == 5 && version.minor >= 2)))
#endif
        } else {
            // Swift version detection may fail but it doesn't cause any wrong result then it should pass the test.
            XCTAssertTrue(true)
        }
    }
```
As I wrote in the test doc. The test actually runs only one of the assertions but I think it's better than nothing :)

Should I commit this?

**Comment by 0xTim** [comment]
Yep there's never too many tests!

**Comment by Ventus218** [comment]
> Yep there's never too many tests!

Test added here 5f5d881.

If Github tests succeed then the PR is ready to be merged.

**Comment by 0xTim** [comment]
Cool will release this alongside the other PRs

**Comment by Ventus218** [comment]
@0xTim 

Thank you for your help during this PR, this was my absolute first contribution.

So happy right now :)

**Comment by 0xTim** [comment]
Happy to help. Thanks for contributing!

**Pull request merged**
