### PR TITLE
vapor toolbox 2018, built on SPM libs

### PR DESCRIPTION
**Pull request by tanner0101**
- [x] implement vapor xcode command

### CODE REVIEW

**Comment by joscdk** [comment]
@CamJN what are you trying to accomplish? ..

**Comment by CamJN** [comment]
I'm trying to build the toolkit from source on debian 9. I've already gotten swift  4.2.1 built and working, so I was hoping to be able to get the vapor stuff working too.

**Comment by joscdk** [comment]
@CamJN the distribute command is only to setup a new release for Mac. To setup the Toolbox, clone the repo down locally, and run
```
swift build -c release
```
And copy the Executable file to `/usr/local/bin` as the name `vapor`

**Comment by joscdk** [comment]
If you have problems with that, open an issue, and tag me, so we don't spam this PR with unrelated issues :)

**Comment by calebkleveter** [comment]
@CamJN My guess is that you don't have SSH setup on your machine. SPM freezes up when you have a dependency with an SSH URI and you don't have it configured. I wish it spit out an error, but oh well.

**Comment by loganwright** [comment]
closing this temporarily, going to revisit spm direct integration when it's a bit more stable which it sounds like it already might be

**Pull request closed without merging**
