### PR TITLE
Tests 3

### PR DESCRIPTION
**Pull request by feinstruktur**
Next batch of tests and some cleanup

### CODE REVIEW

**Comment by tannernelson** [comment]
I'm still working on merging / copying these changes over. The testing paradigm is a bit different with the updated qutheory/console repository.

**Comment by feinstruktur** [comment]
Great, thanks! I haven't had a chance to take a look at all your changes in detail (just that there were many), please let me know if you have any questions.

**Comment by LoganWright** [comment]
@tannernelson what does it take to get these integrated?

**Comment by LoganWright** [comment]
These were integrated through separate PRs over time, I think we can safely close this for now. Thanks for the great stuff as always!!

**Pull request closed without merging**
