### PR TITLE
Changing Slack

### PR DESCRIPTION
**Pull request by joscdk**
If we tag another release, let's make this small change to remove "Slack" from two messages.

Nothing urgent.

### CODE REVIEW

**Comment by grundoon** [comment]
Why remove the badge altogether, instead of changing to

 ```html
    <a href="https://discord.gg/vapor">
        <img src="https://img.shields.io/discord/431917998102675485.svg" alt="Team Chat">
    </a>
 ```

(no biggie, just wondering)

**Comment by joscdk** [comment]
@grundoon ahh i missed that :D .. It's added now :)

**Comment by LoganWright** [comment]
Looks great, LGTM

**Comment by penny-coin** [comment]
Hey @joscdk, you just merged a pull request, have a coin! 

You now have 327 coins.

**Pull request merged**
