### PR TITLE
Fix Swift 4.1 issues, Procfile for Vapor 3, and switch to CircleCI

### PR DESCRIPTION
**Pull request by kdawgwilk**
Arguments have changed for Vapor 3 and this fixes one of the issues with Heroku deploy

### CODE REVIEW

**Comment by joscdk** [comment]
Hmm should it maybe ask if you want Vapor 2 or Vapor 3, just so we don't break Vapor 2 :)

**Comment by bre7** [comment]
Extract project's Vapor framework version: https://github.com/vapor/toolbox/blob/master/Sources/VaporToolbox/Version.swift#L43

**Comment by vzsg** [comment]
One more thing, the Procfile should be updated to include the `serve` command as it isn't implied anymore if there are other arguments.

```
web: Run serve --hostname 0.0.0.0 --port $PORT
```

**Comment by vzsg** [comment]
(I mean `\(appName)` instead of Run, of course, but cannot edit.)

**Comment by kdawgwilk** [comment]
Alright added major version check that will change the Procfile for different Vapor versions.  I also tried to fix CI but it seemed futile since all other Vapor projects use Circle CI instead of Travis.  If someone that can flip that switch on for this repo that would be great 👍

**Comment by kdawgwilk** [comment]
Build failed here:
```
/root/project/Sources/Cloud/Commands/Playground.swift:592:20: error: cannot convert value of type 'ObjCBool' to expected argument type 'Bool'
            guard !isDirectory else { return }
```
At least I am getting somewhere

**Comment by kdawgwilk** [comment]
isn't that `//$PORT` a comment though so the hostname would be ignored if it came after that?

**Comment by bre7** [comment]
👍 (procfiles support comments?)
```swift
procContents = "web: \(appName) serve --env production --port $PORT --hostname 0.0.0.0"
```

**Pull request merged**
