### PR TITLE
Added ability to choose deployment region for new Heroku apps

### PR DESCRIPTION
**Pull request by Tombio**
This PR adds ability to create Heroku app to other regions than "us" (Heroku default)

### CODE REVIEW

**Comment by LoganWright** [comment]
@Tombio thanks for contributing to Vapor! I have some questions, does the procfile modify the location of the server, it seems like the procfile would run after a server instance and region has already been decided, no?

Maybe I'm wrong, if so, would you mind linking to some heroku docs referencing where this is decided?

**Comment by Tombio** [comment]
@LoganWright You are correct. Region is chosen when creating application. I'll post a fix later.

**Comment by sadiq81** [comment]
Bump

**Comment by vzsg** [comment]
Here's the link to the documentation: [Regions](https://devcenter.heroku.com/articles/regions)

While `us`/`eu` is enough for the Common Runtime, it would be best if the output from `heroku regions` could be parsed to show the available options to the user. Or just displayed as a table.

**Comment by LoganWright** [comment]
Sorry about the crazy late merge @Tombio thanks for the contribution!

**Pull request merged**
