### PR TITLE
Fix Package.resolved version decoding issue

### PR DESCRIPTION
**Pull request by Kyle-Ye**
Fixes issue when trying to decode V2 Package.resolved files

### CODE REVIEW

**Comment by 0xTim** [comment]
@Kyle-Ye I'm assuming you've tested this locally with a recent Swift version?

**Comment by 0xTim** [comment]
Original comment

**Comment by Kyle-Ye** [comment]
> @Kyle-Ye I'm assuming you've tested this locally with a recent Swift version?

No, I can reproduce this with multi Swift version. And the Package.resolved is always v1.

**Comment by 0xTim** [comment]
OK cool but this fixes it? I can't get a v2, might be in 5.7 which we can fix later if needed

**Comment by Kyle-Ye** [comment]
Yes, v2 removeremoves the object defination. We could solve it later when Swift 5.7 landded.

image

**Review by 0xTim — APPROVED** [review]

**Pull request merged**
